### PR TITLE
Fix #167 and other misc changes

### LINKED ISSUE #167: ClassCastException occurs when connected node does not use SeLionRemoteProxy
When there is a node which does not use `SeLionRemoteProxy` connected to a SeLion enhanced hub/server a `ClassCastException` will occur in `GridForceRestartDelegateServlet` and `GridAutoUpgradeDelegateServlet`

### PR DESCRIPTION
**Pull request by mach6**
Additional changes include;
- Correct some javadoc issues
- Remove checks for Grid.driver() != null.. This is not a valid
  condition anymore
- Remove dead code in SeLionReporter
- Add missing ListenerManager check to RuntimeReporterListner.onStart

### CODE REVIEW

**Comment by mach6** [comment]
@sebady @sundaramrajendran Please review

File: client/src/main/java/com/paypal/selion/platform/utilities/WebDriverWaitUtils.java [hunk 1]
```diff
@@ -67,7 +64,6 @@ private static void waitForCondition(ExpectedCondition<?> condition, long timeou
      */
     public static void waitUntilElementIsClickable(final String elementLocator) {
         logger.entering(elementLocator);
-        Preconditions.checkState(Grid.driver() != null, INVALID_STATE_ERR_MSG);
```
Comment (sebady) [inline client/src/main/java/com/paypal/selion/platform/utilities/WebDriverWaitUtils.java:70]: Why not still do a Grid.driver() here just to verify that the driver is initialized to the state we expect here.  Is there another way to confirm the driver is initialized here and in other places?

Comment (mach6) [inline client/src/main/java/com/paypal/selion/platform/utilities/WebDriverWaitUtils.java:70]: The contract for `Grid.driver()` states it will not return `null`. Thus the check is not needed. If you want to check that the `TestSession` is valid, that's a different meaning and is accessible via `Grid.getTestSession()`

File: server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java [hunk 2]
```diff
@@ -114,21 +117,34 @@ protected void process(HttpServletRequest request, HttpServletResponse response)
...
+                    // TODO :: Address the assumption here that any node which uses SeLionRemoteProxy also has
+                    // NodeAutoUpgradeServlet available. Without truth in this assumption, the call to
+                    // proxy.release() will do nothing.
+                    try {
+                        SeLionRemoteProxy proxy = (SeLionRemoteProxy) eachProxy;
+                        if (!proxy.release(downloadJSON)) {
+                            pendingProxy.add(proxy.getId());
+                        }
+                    } catch (ClassCastException e) {
+                        // ignore, node is not likely compatible with NodeAutoUpgradeServlet
```
Comment (sundaramrajendran) [inline server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java]: @mach6 I think we can log the exception, because it will helpful when debugging.

File: server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java [hunk 3]
```diff
@@ -114,21 +117,34 @@ protected void process(HttpServletRequest request, HttpServletResponse response)
...
+                    // proxy.release() will do nothing.
+                    try {
+                        if (!eachId.trim().isEmpty()) {
+                            SeLionRemoteProxy proxy = (SeLionRemoteProxy) getRegistry().getProxyById(eachId.trim());
+                            if ((proxy != null) && (!proxy.release(downloadJSON))) {
+                                pendingProxy.add(proxy.getId());
+                            }
                         }
+                    } catch (ClassCastException e) {
+                        // ignore, node is not likely compatible with NodeAutoUpgradeServlet
```
Comment (sundaramrajendran) [inline server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java]: @mach6 Here too, log the exception applicable places

File: server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java [hunk 4]
```diff
@@ -114,21 +117,34 @@ protected void process(HttpServletRequest request, HttpServletResponse response)
...
-                        pendingProxy.add(proxy.getId());
+                    // TODO :: Address the assumption here that any node which uses SeLionRemoteProxy also has
+                    // NodeAutoUpgradeServlet available. Without truth in this assumption, the call to
+                    // proxy.release() will do nothing.
+                    try {
+                        SeLionRemoteProxy proxy = (SeLionRemoteProxy) eachProxy;
+                        if (!proxy.release(downloadJSON)) {
+                            pendingProxy.add(proxy.getId());
+                        }
+                    } catch (ClassCastException e) {
```
Comment (sundaramrajendran) [inline server/src/main/java/com/paypal/selion/grid/servlets/GridAutoUpgradeDelegateServlet.java]: @mach6 Instead of catching ClassCastException, We can add if condition to verify is this instance of SeLionRemoteProxy and execute the code. Else condition log the information for user about "Node incompatible for AutoUpgrade"

**Comment by mach6** [comment]
@sundaramrajendran thanks for the feedback. I made the changes you suggested
