### PR TITLE
Fix #184 - SeLion Android elements are not custom elements

### LINKED ISSUE #184: code-generator does not work for PageYaml with "android" platform
From http://paypal.github.io/SeLion/html/documentation.html#android-native-page-yaml

This (corrected with ending `"` on locators) example PageYaml does not work

``` yaml
baseClass: "com.paypal.selion.testcomponents.BasicPageImpl"
platform: "android"
defaultLocale: "US"
elements:
  shortPressButtonUiObject:
    locators:
      FR: "//TintButton[@value='Short Press']"
      US: "//TintButton[@value='Short Press']"
  shortPressLabelUiObject:
    locators:
      FR: "//TextView[contains(@value, ', short press')]"
      US: "//TextView[contains(@value, ', short press')]"
```

the resulting error is 

``` shell
[ERROR] SeLion code generator failed when generating code for {file}
[ERROR] Root Cause :
[ERROR] java.lang.IllegalArgumentException: Detected an invalid key [shortPressLabelUiObject] in data file {file} for Platform Android
```

### PR DESCRIPTION
**Pull request by mach6**
- Added SeLion default Android elements (UiObject, UiTextView, UiButton)
  to AndroidSeLionElementList of codegen. Previously, they were treated
  as custom elements.. which should not have been the case
- Also added UIAElement to IOSSelionElementList
- Misc formatting changes

### CODE REVIEW

File: codegen/src/main/java/com/paypal/selion/elements/AndroidSeLionElementList.java [hunk 1]
```diff
@@ -22,54 +22,67 @@
...
      */
     public static void registerElement(String element) {
         List<AndroidSeLionElementList> temp = new ArrayList<AndroidSeLionElementList>(Arrays.asList(values));
-        
-        temp.add(0, new AndroidSeLionElementList(HtmlElementUtils.getPackage(element), HtmlElementUtils.getClass(element), true));
-        
+
+        temp.add(0,
+                new AndroidSeLionElementList(HtmlElementUtils.getPackage(element), HtmlElementUtils.getClass(element),
+                        true));
```
Comment (mach6) [inline codegen/src/main/java/com/paypal/selion/elements/AndroidSeLionElementList.java:53]: ick.. I don't like that this split across 3 lines.. will fix it

File: codegen/src/main/java/com/paypal/selion/elements/AndroidSeLionElementList.java [hunk 2]
```diff
@@ -22,54 +22,67 @@
...
+            new AndroidSeLionElementList(UIAUTOMATION_ELEMENT_CLASS, "UiTextField", true);
+    public static AndroidSeLionElementList UiObject =
+            new AndroidSeLionElementList(UIAUTOMATION_ELEMENT_CLASS, "UiObject", true);
+    public static AndroidSeLionElementList BASE_CLASS =
+            new AndroidSeLionElementList(null, "baseClass", false);
+
+    /**
+     * The android elements are added as custom elements and SeLion does not declare any elements specifically which
+     * explains the empty array to hold the custom elements.
+     */
```
Comment (sebady) [inline codegen/src/main/java/com/paypal/selion/elements/AndroidSeLionElementList.java]: We should update the java doc.

Comment (mach6) [inline codegen/src/main/java/com/paypal/selion/elements/AndroidSeLionElementList.java]: meant to.. will fix
