### PR TITLE
Updates for building on Travis CI and misc bug fixes

### LINKED ISSUE #17: 'client' build tests fail with latest ios-driver-0.6.6-snapshot code on 'dev' branch
The ios-server jar is no longer a jar-with-dependencies. As a result, we have some classpath related issues when TestServerUtils attempts to start.

The fix here seems to be;
1. exclude selenium-server in the 'client' pom from the ios-server dependency declaration
2. go back to `import org.seleniumhq.jetty7.x` in `TestServerUtils.java`

### LINKED ISSUE #18: error "unsupported command-line --ignore-certificate-errors" displayed in chrome
This seems to be an issue that popped up since selenium 2.41+

### LINKED ISSUE #19: Error displayed in SeLIon Grid2 Node on windows
15:55:36.308 ERROR - java.io.IOException: Cannot run program "tasklist.exe /fo c
sv /nh": CreateProcess error=2, The system cannot find the file specified
com.paypal.selion.utils.process.ProcessHandlerException: java.io.IOException: Ca
nnot run program "tasklist.exe /fo csv /nh": CreateProcess error=2, The system c
annot find the file specified

### LINKED ISSUE #20: chromedriver not found by SeLion local Grid2 node when running on windows
There is a hard-coded assumption in the 'server' start-up script that the binaries will be a C:\Grid2. This assumption is not valid.

### PR DESCRIPTION
**Pull request by mach6**
- Corrected some misc issues with the test suites
- Add phantomjs to defualt grid config
- Add install-ios-driver shell script for cloning, building, and
  installing ios-driver to local maven repository
- fix #17 - issues running SeLion client tests since latest ios-driver
  SNAPSHOT
- fix #18 - unsupported command-line displayed in chrome
- fix #19 - issues with WindowsProcessHandler
- fix #20 - chromedriver not found due to hard-coded assumption in
  SeLion server component

### CODE REVIEW

File: server/src/main/java/com/paypal/selion/utils/process/AbstractProcessHandler.java [hunk 1]
```diff
@@ -77,11 +77,13 @@
         return processToBeKilled;
     }
 
-    protected void killProcess(String killCommand, List<ProcessInfo> process) throws ProcessHandlerException {
+    protected void killProcess(String[] killCommand, List<ProcessInfo> process) throws ProcessHandlerException {
         try {
             for (ProcessInfo eachProcess : process) {
                 log.info("Killing process : " + eachProcess);
-                Process output = Runtime.getRuntime().exec(killCommand + " " + eachProcess.getProcessId());
+                String[] cmd = new String[killCommand.length + 1];
```
Comment (sebady) [inline server/src/main/java/com/paypal/selion/utils/process/AbstractProcessHandler.java]: Don't we need to copy the kill command array here into cmd?
